'use client';

import React from 'react';
import { ModalSection } from '@/components/ui/Modal';
import { BasicInfoSectionProps } from '../types';

const errorBorder = 'border-red-500 focus:ring-red-500';
const normalBorder = 'border-sf-border focus:ring-sf-accent';

export function BasicInfoSection({
  formData,
  setFormData,
  t,
  nameInputRef,
  slugModified,
  setSlugModified,
  currentDomain,
  generateSlug,
  fieldErrors = {},
}: BasicInfoSectionProps) {
  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const { name, value } = e.target;

    if (name === 'name' && !slugModified) {
      setFormData((prev) => ({
        ...prev,
        [name]: value,
        slug: generateSlug(value),
      }));
    } else if (name === 'slug') {
      setSlugModified(true);
      setFormData((prev) => ({
        ...prev,
        [name]: generateSlug(value),
      }));
    } else {
      setFormData((prev) => ({
        ...prev,
        [name]: value,
      }));
    }
  };

  return (
    <ModalSection title={t('basicInformation')}>
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <div>
          <label htmlFor="name" className="block text-sm font-medium text-sf-body mb-2">
            {t('productName')}
          </label>
          <input
            type="text"
            id="name"
            name="name"
            value={formData.name}
            onChange={handleInputChange}
            ref={nameInputRef}
            className={`w-full px-3 py-2.5 border ${
              fieldErrors.name ? errorBorder : normalBorder
            } focus:outline-none focus:ring-2 focus:border-transparent bg-sf-input text-sf-heading`}
            placeholder={t('enterProductName')}
            required
          />
          {fieldErrors.name && (
            <p className="mt-1 text-xs text-red-500">
              {t('nameRequired', { name: t('productName') })}
            </p>
          )}
        </div>

        <div>
          <label htmlFor="slug" className="block text-sm font-medium text-sf-body mb-2">
            {t('urlSlug')}
            <span className="text-xs text-sf-muted ml-1">({t('autoGenerated')})</span>
          </label>
          <div className="relative">
            <input
              type="text"
              id="slug"
              name="slug"
              value={formData.slug}
              onChange={handleInputChange}
              className={`w-full px-3 py-2.5 border ${
                fieldErrors.slug ? errorBorder : normalBorder
              } focus:outline-none focus:ring-2 focus:border-transparent bg-sf-input text-sf-heading pr-12`}
              placeholder={t('slugPlaceholder')}
              required
            />
            {!slugModified && (
              <span className="absolute right-3 top-1/2 transform -translate-y-1/2 text-xs text-sf-accent bg-sf-accent-soft px-2 py-1">
                {t('autoSlug')}
              </span>
            )}
          </div>
          <p className="mt-1 text-xs text-sf-muted">
            {currentDomain ? `${currentDomain}/p/` : 'https://example.com/p/'}
            <strong>{formData.slug || 'product-slug'}</strong>
          </p>
        </div>
      </div>
    </ModalSection>
  );
}
