/**
 * Captures professional screenshots for README and landing page.
 *
 * Requires: local Supabase running + dev server on localhost:3000
 * Run: cd admin-panel && npx tsx scripts/capture-screenshots.ts
 *
 * The script inserts polished demo data, captures, then resets the DB
 * so seed data is back to normal for tests.
 */
import { chromium } from 'playwright';
import { createClient } from '@supabase/supabase-js';
import * as path from 'path';
import { fileURLToPath } from 'url';
import { execSync } from 'child_process';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const BASE_URL = 'http://localhost:3000';
const SUPABASE_URL = 'http://127.0.0.1:54321';
const SERVICE_ROLE_KEY = 'sb_secret_N7UND0UgjKTVK-Uodkm0Hg_xSvEMPvz';
const ANON_KEY = 'sb_publishable_ACJWlzQHlZjBrEguHvfOxg_3BJgxAaH';
const OUTPUT_DIR = path.join(__dirname, '..', 'public', 'screenshots');
const REPO_ROOT = path.join(__dirname, '..', '..');

const supabaseAdmin = createClient(SUPABASE_URL, SERVICE_ROLE_KEY);

// ===== Pages to capture =====

interface PageSpec {
  path: string;
  filename: string;
  /** Playwright actions to run after page load (e.g., filter dropdowns) */
  afterLoad?: (page: import('playwright').Page) => Promise<void>;
}

/** Select "Active" in the Status dropdown on the products page */
async function filterProductsActive(page: import('playwright').Page) {
  await page.locator('#status-filter').selectOption('active');
  await page.waitForTimeout(1000);
}

const LIGHT_PAGES: PageSpec[] = [
  { path: '/dashboard', filename: 'dashboard.png' },
  { path: '/dashboard/products', filename: 'products.png', afterLoad: filterProductsActive },
  { path: '/dashboard/settings', filename: 'settings.png' },
  { path: '/', filename: 'storefront.png' },
  { path: '/checkout/premium-course', filename: 'checkout.png' },
];

const DARK_PAGES: PageSpec[] = [
  { path: '/dashboard', filename: 'dashboard-dark.png' },
  { path: '/dashboard/products', filename: 'products-dark.png', afterLoad: filterProductsActive },
];

// ===== Demo data setup =====

/**
 * Injects polished demo data for marketing-quality screenshots.
 * - Hides test products (is_listed = false)
 * - Activates VIP Masterclass
 * - Makes good products featured
 * - Inserts realistic payment transactions spread over 30 days
 * - Inserts demo users for user count
 */
async function setupDemoData() {
  console.log('Setting up demo data...');

  // Clear failed webhook logs so the dashboard banner doesn't appear
  await supabaseAdmin.from('webhook_logs').delete().eq('status', 'failed');

  // Hide test-only products, keep the polished ones
  const testProducts = [
    'Test OTO Target', 'Test OTO Active', 'Test OTO Owned',
    'Test Product Redirect', 'Test No Redirect', 'Test Custom Redirect',
  ];
  for (const name of testProducts) {
    await supabaseAdmin.from('products').update({ is_listed: false, is_active: false }).eq('name', name);
  }

  // Hide magnet products (generated by E2E)
  await supabaseAdmin.from('products').update({ is_listed: false, is_active: false }).ilike('name', 'Magnet-%');

  // Activate and feature the good products
  await supabaseAdmin.from('products').update({ is_active: true, is_listed: true, is_featured: true }).eq('name', 'VIP Masterclass');
  await supabaseAdmin.from('products').update({ is_active: true, is_listed: true, is_featured: true }).eq('name', 'Pro Toolkit');
  await supabaseAdmin.from('products').update({ is_active: true, is_listed: true }).eq('name', 'Design System Bundle');
  await supabaseAdmin.from('products').update({ is_active: true, is_listed: true }).eq('name', 'Enterprise Package');

  // Get product IDs for transactions
  const { data: products } = await supabaseAdmin
    .from('products')
    .select('id, name, price')
    .in('name', ['Premium Course', 'Pro Toolkit', 'VIP Masterclass', 'Community Guide', 'Design System Bundle']);

  if (!products?.length) {
    console.warn('No products found for demo transactions');
    return;
  }

  // Create demo users for realistic user count
  const demoUserIds: string[] = [];
  for (let i = 0; i < 40; i++) {
    const { data: { user } } = await supabaseAdmin.auth.admin.createUser({
      email: `demo-user-${i}@sellf-demo.test`,
      password: 'demo123',
      email_confirm: true,
    });
    if (user) demoUserIds.push(user.id);
  }

  // Insert realistic payment transactions spread over 30 days
  const now = new Date();
  const transactions: Array<{
    user_id: string;
    product_id: string;
    amount: number;
    currency: string;
    status: string;
    stripe_payment_intent_id: string;
    session_id: string;
    customer_email: string;
    created_at: string;
  }> = [];

  const names = ['Alice', 'Bob', 'Charlie', 'Diana', 'Eve', 'Frank', 'Grace', 'Henry', 'Ivy', 'Jack',
    'Kate', 'Leo', 'Mia', 'Noah', 'Olivia', 'Paul', 'Quinn', 'Rosa', 'Sam', 'Tara'];

  for (let dayOffset = 30; dayOffset >= 0; dayOffset--) {
    // More transactions in recent days (growth curve)
    const txCount = dayOffset > 20 ? 1 : dayOffset > 10 ? 2 : dayOffset > 5 ? 3 : 5;
    for (let j = 0; j < txCount; j++) {
      const product = products[Math.floor(Math.random() * products.length)];
      if (!product.price || product.price === 0) continue;
      const userIdx = Math.floor(Math.random() * Math.min(demoUserIds.length, 20));
      const date = new Date(now);
      date.setDate(date.getDate() - dayOffset);
      date.setHours(Math.floor(Math.random() * 14) + 8); // 8am-10pm

      const name = names[userIdx % names.length];
      transactions.push({
        user_id: demoUserIds[userIdx] || demoUserIds[0],
        product_id: product.id,
        amount: Math.round(product.price * 100), // DB stores cents
        currency: 'USD',
        status: 'completed',
        stripe_payment_intent_id: `pi_demo_${dayOffset}_${j}_${Date.now()}`,
        session_id: `cs_demo_${dayOffset}_${j}_${Date.now()}`,
        customer_email: `${name.toLowerCase()}@example.com`,
        created_at: date.toISOString(),
      });
    }
  }

  // Insert in batches
  for (let i = 0; i < transactions.length; i += 20) {
    const batch = transactions.slice(i, i + 20);
    await supabaseAdmin.from('payment_transactions').insert(batch);
  }

  console.log(`  Inserted ${transactions.length} demo transactions, ${demoUserIds.length} demo users`);
  console.log(`  Hidden ${testProducts.length} test products, activated showcase products`);
}

// ===== Auth helpers =====

async function createAdmin() {
  const email = 'admin@sellf-demo.com';
  const password = 'password123';

  // Reuse existing user if already created from a previous run
  const { data: { users } } = await supabaseAdmin.auth.admin.listUsers({ perPage: 1000 });
  const existing = users?.find((u) => u.email === email);

  if (existing) {
    // Ensure admin role exists
    await supabaseAdmin.from('admin_users').upsert({ user_id: existing.id }, { onConflict: 'user_id' });
    return { email, password, userId: existing.id };
  }

  const { data: { user }, error } = await supabaseAdmin.auth.admin.createUser({
    email,
    password,
    email_confirm: true,
  });
  if (error) throw error;

  await supabaseAdmin.from('admin_users').insert({ user_id: user!.id });

  return { email, password, userId: user!.id };
}

async function setAuthCookies(context: import('playwright').BrowserContext, email: string, password: string) {
  const signInClient = createClient(SUPABASE_URL, ANON_KEY);
  const { data: { session }, error } = await signInClient.auth.signInWithPassword({ email, password });
  if (error || !session) throw new Error(`Sign-in failed: ${error?.message || 'no session'}`);

  const cookieKey = `sb-${new URL(SUPABASE_URL).hostname.split('.')[0]}-auth-token`;
  const base64Value = `base64-${Buffer.from(JSON.stringify(session)).toString('base64url')}`;

  const CHUNK_SIZE = 3180;
  if (base64Value.length <= CHUNK_SIZE) {
    await context.addCookies([{ name: cookieKey, value: base64Value, domain: 'localhost', path: '/' }]);
  } else {
    const chunks: string[] = [];
    for (let i = 0; i < base64Value.length; i += CHUNK_SIZE) {
      chunks.push(base64Value.substring(i, i + CHUNK_SIZE));
    }
    await context.addCookies(chunks.map((chunk, idx) => ({
      name: `${cookieKey}.${idx}`, value: chunk, domain: 'localhost', path: '/',
    })));
  }
}

async function setConsentCookie(context: import('playwright').BrowserContext) {
  await context.addCookies([{
    name: 'sellf_consent',
    value: JSON.stringify({ 'google-tag-manager': true, 'facebook-pixel': true, 'umami-analytics': true }),
    domain: 'localhost',
    path: '/',
  }]);
}

// ===== Screenshot capture =====

/** CSS injected BEFORE page load to hide noise */
const HIDE_NOISE_CSS = `
  #klaro, .klaro { display: none !important; }
  [class*="bg-sf-danger-soft"] { display: none !important; }
  nextjs-portal { display: none !important; }
  [data-nextjs-toast] { display: none !important; }
  #__next-build-watcher { display: none !important; }
  [class*="nextjs-"] { display: none !important; }
  body > div[style*="position: fixed"][style*="bottom"] { display: none !important; }
`;

async function capture(
  context: import('playwright').BrowserContext,
  pages: PageSpec[],
) {
  const page = await context.newPage();

  // Inject CSS + JS before any navigation to hide dev noise
  await page.addInitScript((css) => {
    const inject = () => {
      if (document.head) {
        const style = document.createElement('style');
        style.textContent = css;
        document.head.appendChild(style);
      } else {
        setTimeout(inject, 10);
      }
    };
    inject();

    // Remove Next.js dev indicator (uses Shadow DOM, CSS can't target it)
    const removeDevIndicator = () => {
      document.querySelectorAll('nextjs-portal').forEach(el => el.remove());
      // The "N Issues" badge
      const allElements = document.querySelectorAll('body > *');
      allElements.forEach(el => {
        if (el.shadowRoot || el.tagName?.toLowerCase().includes('next')) {
          el.remove();
        }
      });
    };
    // Run after page settles
    setTimeout(removeDevIndicator, 1500);
    setTimeout(removeDevIndicator, 2500);

    // Note: sf_sidebar_pinned is set via context.addInitScript in main()
  }, HIDE_NOISE_CSS);

  let sidebarPinned = false;

  for (const { path: pagePath, filename, afterLoad } of pages) {
    const url = `${BASE_URL}/en${pagePath}`;
    console.log(`  ${filename} → ${url}`);

    await page.goto(url, { waitUntil: 'domcontentloaded', timeout: 30_000 });
    // Settle time for React hydration, charts, lazy content
    await page.waitForTimeout(3000);

    // Pin sidebar open on first dashboard page (persists via localStorage for subsequent pages)
    if (!sidebarPinned && pagePath.startsWith('/dashboard')) {
      const sidebar = page.locator('aside').first();
      await sidebar.hover();
      await page.waitForTimeout(400);
      const pinBtn = sidebar.locator('button[aria-label="Pin sidebar open"]');
      if (await pinBtn.isVisible()) {
        await pinBtn.click();
        await page.waitForTimeout(600);
        sidebarPinned = true;
      }
    }

    // Run page-specific actions (e.g., filter dropdowns)
    if (afterLoad) {
      await afterLoad(page);
    }

    // Remove Next.js dev indicator (Shadow DOM element at bottom-left)
    await page.evaluate(() => {
      document.querySelectorAll('nextjs-portal').forEach(el => el.remove());
      document.querySelectorAll('*').forEach(el => {
        if (el.tagName?.toLowerCase().startsWith('nextjs')) el.remove();
      });
    });

    await page.screenshot({
      path: path.join(OUTPUT_DIR, filename),
      fullPage: false,
    });
  }

  await page.close();
}

// ===== Main =====

async function main() {
  await setupDemoData();

  console.log('\nCreating screenshot admin...');
  const admin = await createAdmin();

  const browser = await chromium.launch();

  try {
    // ===== Light theme =====
    console.log('\nCapturing light theme (2x retina)...');
    const lightContext = await browser.newContext({
      viewport: { width: 1920, height: 1080 },
      deviceScaleFactor: 2,
      colorScheme: 'light',
    });
    await lightContext.addInitScript(() => {
      localStorage.setItem('sf_sidebar_pinned', 'true');
    });
    await setConsentCookie(lightContext);
    await setAuthCookies(lightContext, admin.email, admin.password);
    await capture(lightContext, LIGHT_PAGES);
    await lightContext.close();

    // ===== Dark theme =====
    console.log('\nCapturing dark theme (2x retina)...');
    const darkContext = await browser.newContext({
      viewport: { width: 1920, height: 1080 },
      deviceScaleFactor: 2,
      colorScheme: 'dark',
    });
    await darkContext.addInitScript(() => {
      localStorage.setItem('sf_theme', 'dark');
      localStorage.setItem('sf_sidebar_pinned', 'true');
    });
    await setConsentCookie(darkContext);
    await setAuthCookies(darkContext, admin.email, admin.password);
    await capture(darkContext, DARK_PAGES);
    await darkContext.close();

  } finally {
    await browser.close();
  }

  // Optimize PNGs
  console.log('\nOptimizing PNGs with pngquant...');
  try {
    execSync(`pngquant --quality=80-100 --force --ext .png ${path.join(OUTPUT_DIR, '*.png')}`, {
      stdio: 'inherit',
    });
    console.log('Optimization complete.');
  } catch {
    console.warn('pngquant not found or failed — skipping optimization.');
  }

  console.log(`\nDone! Screenshots saved to: ${OUTPUT_DIR}`);
}

main().catch((err) => {
  console.error('Screenshot capture failed:', err);
  process.exit(1);
});
